const missions = [
  {
    title: "Defesa da Cidade",
    description:
      "A cidade está sendo atacada por monstros e precisa de heróis para defendê-la.",
    objectives: ["Derrotar os monstros invasores", "Proteger os cidadãos"],
    rewards: ["Espada mágica", "200 pontos de experiência"],
    difficulty: "Difícil",
    location: "Cidade de Eldoria",
    prerequisites: ["Habilidade em combate", "Força e coragem"],
    status: "Ativa",
    notes: "Monstros podem atacar em ondas.",
  },
  {
    title: "Recuperação de Artefato",
    description:
      "Um artefato antigo de grande poder foi roubado e precisa ser recuperado antes que caia em mãos erradas.",
    objectives: ["Rastrear o ladrão", "Recuperar o artefato"],
    rewards: ["Artefato restaurado", "300 pontos de experiência"],
    difficulty: "Médio",
    location: "Ruínas de Arkania",
    prerequisites: [
      "Conhecimento de história e arqueologia",
      "Habilidade de rastreamento",
    ],
    status: "Ativa",
    notes: "Cuidado com armadilhas nas ruínas.",
  },
  {
    title: "Expansão da Fronteira",
    description:
      "É necessário explorar e colonizar novas terras além da fronteira para o crescimento do reino.",
    objectives: ["Mapear a região", "Estabelecer um posto avançado"],
    rewards: ["Terras férteis", "150 pontos de experiência"],
    difficulty: "Fácil",
    location: "Terras Inexploradas",
    prerequisites: ["Equipe de exploradores", "Suprimentos adequados"],
    status: "Ativa",
    notes: "Explorar com cautela.",
  },
  {
    title: "Desafio do Labirinto",
    description:
      "Um labirinto misterioso foi descoberto e desafia os aventureiros corajosos a superá-lo.",
    objectives: ["Navegar pelo labirinto", "Alcançar o centro"],
    rewards: ["Tesouro oculto", "250 pontos de experiência"],
    difficulty: "Médio",
    location: "Labirinto dos Antigos",
    prerequisites: ["Habilidade em labirintos", "Paciência e astúcia"],
    status: "Ativa",
    notes: "Cuidado com as ilusões do labirinto.",
  },
  {
    title: "Paz entre Reinos",
    description:
      "Negociações diplomáticas são necessárias para estabelecer paz entre reinos vizinhos em conflito.",
    objectives: [
      "Negociar um tratado de paz",
      "Resolver disputas territoriais",
    ],
    rewards: ["Paz duradoura", "500 pontos de experiência"],
    difficulty: "Difícil",
    location: "Salão dos Reis",
    prerequisites: ["Habilidade diplomática", "Conhecimento político"],
    status: "Ativa",
    notes: "A diplomacia requer tato e sabedoria.",
  },
  {
    title: "Caça ao Monstro",
    description:
      "Um monstro lendário está aterrorizando as aldeias e precisa ser derrotado.",
    objectives: ["Localizar o covil do monstro", "Derrotar o monstro"],
    rewards: ["Glória eterna", "1000 pontos de experiência"],
    difficulty: "Muito Difícil",
    location: "Montanhas Sombrias",
    prerequisites: ["Força incomparável", "Determinação implacável"],
    status: "Ativa",
    notes: "O monstro é extremamente perigoso.",
  },
];

const characters = [
  {
    name: "Aldric Stronghammer",
    class: "Guerreiro",
    level: 10,
    attributes: {
      strength: 18,
      dexterity: 14,
      constitution: 16,
      intelligence: 10,
      wisdom: 12,
      charisma: 10,
    },
    skills: ["Espada Longa", "Armadura Pesada", "Liderança"],
    equipment: ["Espada Longa +2", "Armadura Completa", "Escudo de Aço"],
    gold: 500,
    experience: 15000,
  },
  {
    name: "Lyra Shadowcloak",
    class: "Ladina",
    level: 8,
    attributes: {
      strength: 10,
      dexterity: 20,
      constitution: 12,
      intelligence: 14,
      wisdom: 10,
      charisma: 16,
    },
    skills: ["Furtividade", "Armadilhas", "Persuasão"],
    equipment: [
      "Adagas Envenenadas",
      "Armadura Leve",
      "Anel da Invisibilidade",
    ],
    gold: 700,
    experience: 12000,
  },
  {
    name: "Thalgorin Thunderforge",
    class: "Mago",
    level: 12,
    attributes: {
      strength: 8,
      dexterity: 12,
      constitution: 10,
      intelligence: 20,
      wisdom: 14,
      charisma: 10,
    },
    skills: ["Magia Arcana", "Elementalismo", "Alquimia"],
    equipment: ["Cajado Arcano", "Robe de Bruxo", "Livro de Feitiços"],
    gold: 1000,
    experience: 20000,
  },
  {
    name: "Sariel Lightbringer",
    class: "Clériga",
    level: 9,
    attributes: {
      strength: 12,
      dexterity: 10,
      constitution: 14,
      intelligence: 14,
      wisdom: 18,
      charisma: 16,
    },
    skills: ["Cura", "Proteção Divina", "Exorcismo"],
    equipment: ["Cajado Sagrado", "Armadura de Fé", "Tomo Sagrado"],
    gold: 600,
    experience: 16000,
  },
  {
    name: "Drakkar Bloodrage",
    class: "Bárbaro",
    level: 7,
    attributes: {
      strength: 20,
      dexterity: 14,
      constitution: 18,
      intelligence: 8,
      wisdom: 10,
      charisma: 12,
    },
    skills: ["Fúria Berserk", "Ataque Selvagem", "Resistência Imbatível"],
    equipment: [
      "Machado de Batalha",
      "Peitoral de Couro de Dragão",
      "Poção de Força",
    ],
    gold: 400,
    experience: 10000,
  },
  {
    name: "Elara Swiftwind",
    class: "Ranger",
    level: 6,
    attributes: {
      strength: 14,
      dexterity: 18,
      constitution: 16,
      intelligence: 12,
      wisdom: 16,
      charisma: 12,
    },
    skills: ["Arco e Flecha", "Rastreamento", "Furtividade"],
    equipment: ["Arco Élfico", "Túnica de Peles", "Anel do Predador"],
    gold: 300,
    experience: 8000,
  },
];

export { missions, characters };
