// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Victor Motta",
            "url": "https://github.com/mottapng",
            "email": "victormotta7@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Realiza o login de um usuário com base no email e senha fornecidos.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Realiza o login de um usuário",
                "parameters": [
                    {
                        "description": "Dados de Autenticação",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/authUseCases.LoginBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login realizado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "400": {
                        "description": "Email não encontrado ou senha incorreta",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro ao realizar o login",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Solicita o cadastro de um novo aventureiro, se for o primeiro aventureiro cadastrado, será assumido como o mestre",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Cria um novo aventureiro",
                "parameters": [
                    {
                        "description": "Dados do aventureiro",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/authUseCases.RegisterBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Aventureiro criado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/models.Aventureiro"
                        }
                    },
                    "400": {
                        "description": "Email já cadastrado",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro ao criar aventureiro",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/aventureiros": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Busca aventureiros com base nos parâmetros fornecidos (Requer ser Mestre).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Aventureiro"
                ],
                "summary": "Busca aventureiros (Mestre)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nome do aventureiro",
                        "name": "nome",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Classe do aventureiro",
                        "name": "classe",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Status de aceitação do aventureiro",
                        "name": "aceito",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Número da página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Tamanho da página",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Ordenação dos resultados",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Aventureiros buscados com sucesso",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Aventureiro"
                            }
                        }
                    },
                    "401": {
                        "description": "Não Autorizado",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Header de autorização não encontrado",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro ao buscar aventureiros",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/aventureiros/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Busca um aventureiro com base nos parâmetros fornecidos.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Aventureiro"
                ],
                "summary": "Busca um aventureiro",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do aventureiro",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Aventureiro buscado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/models.Aventureiro"
                        }
                    },
                    "401": {
                        "description": "Não Autorizado",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Header de autorização não encontrado",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro ao buscar aventureiro",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Deleta um aventureiro com base no ID fornecido.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Aventureiro"
                ],
                "summary": "Deleta um aventureiro",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do aventureiro a ser deletado",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Aventureiro deletado com sucesso"
                    },
                    "401": {
                        "description": "Não Autorizado",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Você não tem permissão para deletar este aventureiro",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Header de autorização não encontrado",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro ao buscar aventureiro\" \"Erro ao deletar aventureiro",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Atualiza um aventureiro com base nos dados fornecidos.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Aventureiro"
                ],
                "summary": "Atualiza um aventureiro",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do aventureiro a ser atualizado",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados do aventureiro",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/aventureiroUseCases.UpdateBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Aventureiro atualizado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/models.Aventureiro"
                        }
                    },
                    "400": {
                        "description": "Nome ou classe é obrigatório",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não Autorizado",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Você não tem permissão para atualizar este aventureiro",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Header de autorização não encontrado",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro ao buscar aventureiro\" \"Erro ao atualizar aventureiro",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/aventureiros/{id}/aceitar": {
            "patch": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Aceita um aventureiro com base no ID fornecido.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Aventureiro"
                ],
                "summary": "Aceita aventureiro (Mestre)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do aventureiro",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Aventureiro aceito com sucesso",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "400": {
                        "description": "Aventureiro já aceito",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não Autorizado",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Header de autorização não encontrado",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro ao aceitar aventureiro",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/missoes": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Busca missões com base nos parâmetros fornecidos.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Missão"
                ],
                "summary": "Busca missões",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Título da missão",
                        "name": "titulo",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Dificuldade da missão",
                        "name": "dificuldade",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Nível mínimo requerido",
                        "name": "nivel",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Status da missão (se não for mestre, apenas 'Aberto')",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pontos de experiência",
                        "name": "quantXP",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Número da página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Tamanho da página",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Ordem de classificação dos resultados",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Missões buscadas com sucesso",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Missao"
                            }
                        }
                    },
                    "401": {
                        "description": "Não Autorizado",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Usuário não é o mestre",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Header de autorização não encontrado",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro ao buscar missões",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Cria uma nova missão com base nos dados fornecidos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Missão"
                ],
                "summary": "Cria uma nova missão (Mestre)",
                "parameters": [
                    {
                        "description": "Dados da missão",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/missaoUseCases.CreateMissaoBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Missão criada com sucesso",
                        "schema": {
                            "$ref": "#/definitions/models.Missao"
                        }
                    },
                    "400": {
                        "description": "Dificuldade inválida",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não Autorizado",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Usuário não é o mestre",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Header de autorização não encontrado",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro ao criar a missão",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/missoes/{id}/join": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Adiciona o aventureiro logado em uma missão em aberto",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Missão"
                ],
                "summary": "Adiciona aventureiro logado a uma missão",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da missão",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Aventureiro adicionado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/models.Missao"
                        }
                    },
                    "400": {
                        "description": "Missão cheia",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não Autorizado",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Header de autorização não encontrado",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro ao buscar aventureiro",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/missoes/{id}/updateStatus": {
            "patch": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Atualiza o status da missão (Aberto -\u003e Em andamento -\u003e Concluido)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Missão"
                ],
                "summary": "Atualiza o status de uma missão (Mestre)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da missão",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Missão atualizada com sucesso",
                        "schema": {
                            "$ref": "#/definitions/models.Missao"
                        }
                    },
                    "400": {
                        "description": "Status inválido",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não Autorizado",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Usuário não é o mestre",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Header de autorização não encontrado",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro ao atualizar o status da missão",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "authUseCases.LoginBody": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "senha": {
                    "type": "string"
                }
            }
        },
        "authUseCases.RegisterBody": {
            "type": "object",
            "properties": {
                "classe": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "senha": {
                    "type": "string"
                }
            }
        },
        "aventureiroUseCases.UpdateBody": {
            "type": "object",
            "properties": {
                "classe": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                }
            }
        },
        "missaoUseCases.CreateMissaoBody": {
            "type": "object",
            "properties": {
                "descricao": {
                    "type": "string"
                },
                "dificuldade": {
                    "type": "string"
                },
                "local": {
                    "type": "string"
                },
                "maxParticipantes": {
                    "type": "integer"
                },
                "nivelMinimo": {
                    "type": "integer"
                },
                "quantXP": {
                    "type": "integer"
                },
                "titulo": {
                    "type": "string"
                }
            }
        },
        "models.Aventureiro": {
            "type": "object",
            "properties": {
                "aceito": {
                    "type": "boolean"
                },
                "classe": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "destreza": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "experiencia": {
                    "type": "integer"
                },
                "forca": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "inteligencia": {
                    "type": "integer"
                },
                "mestre": {
                    "type": "boolean"
                },
                "nivel": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "senha": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.Missao": {
            "type": "object",
            "properties": {
                "aventureiros": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Aventureiro"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "descricao": {
                    "type": "string"
                },
                "dificuldade": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "local": {
                    "type": "string"
                },
                "maxParticipantes": {
                    "type": "integer"
                },
                "nivelMinimo": {
                    "type": "integer"
                },
                "quantXP": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "titulo": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "utils.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "utils.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Digite \"Bearer \" seguido do token JWT.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Desafio Estágio API",
	Description:      "Esta API fornece uma plataforma para o gerenciamento de uma guilda em um mundo RPG. Ela permite que os usuários criem e gerenciem personagens (aventureiros) e missões. O sistema calculará e atualizará automaticamente os níveis e atributos dos personagens com base nas missões que eles completam. O primeiro usuário cadastrado será o Mestre da guilda, e terá permissões especiais para gerenciar missões e aventureiros.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
